title: Seth & Jess
description: > # this means to ignore newlines until "baseurl:"
  We're two programmers exploring the world and working remotely. We write about our travels, our work, the people we meet, and the global tech scene.
permalink: ':year/:month/:day/:title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.sethandjess.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Seth Puckett & Jessica Bell # add your name
author-img: seth-and-jess.png # add your photo
about-author: We're two programmers exploring the world and working remotely. We write about our travels, our work, the people we meet, and the global tech scene.
social-twitter-seth: sethpuckett
social-instagram-seth: sethpuckett
social-github-seth: sethpuckett
social-linkedin-seth: sethpuckett
social-email-seth: puckett.seth@gmail.com
social-twitter-jess: sirjessthebrave
social-instagram-jess: sirjessthebrave
social-github-jess: sirjessthebrave
social-linkedin-jess: jessbell317
social-email-jess: jess.bell317@gmail.com

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
